# Generated by Django 4.1.3 on 2022-12-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
            ],
        ),
    ]
